networks:
  postgresql:
    driver: bridge

volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
  pgadmin:
    driver: local

services:
  pg-0:
    image: bitnami/postgresql-repmgr:14
    container_name: "pgrepmgr0"
    ports:
      - 5433:5432
    env_file:
      - ./env/pgs.env
    environment:
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_PORT_NUMBER=5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "127.0.0.1", "-p", "5432"]
      interval: 30s  # 每 30 秒执行一次检查
      timeout: 10s   # 10 秒内必须响应
      retries: 5     # 连续 5 次失败则认为服务不健康
      start_period: 15s  # 在服务启动后的 15 秒内不执行健康检查
    volumes:
      - pg_0_data:/bitnami/postgresql
    restart: unless-stopped
    networks:
      - postgresql

  pg-1:
    image: bitnami/postgresql-repmgr:14
    container_name: "pgrepmgr1"
    ports:
      - 5434:5432
    env_file:
      - ./env/pgs.env
    environment:
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "127.0.0.1", "-p", "5432"]
      interval: 30s  # 每 30 秒执行一次检查
      timeout: 10s   # 10 秒内必须响应
      retries: 5     # 连续 5 次失败则认为服务不健康
      start_period: 15s  # 在服务启动后的 15 秒内不执行健康检查
    volumes:
      - pg_1_data:/bitnami/postgresql
    restart: unless-stopped
    networks:
      - postgresql

  pgpool:
    image: bitnami/pgpool:4
    container_name: "pgpool"
    ports:
      - 5432:5432
    env_file:
      - ./env/pgs.env
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    restart: always
    depends_on:
      - pg-0
      - pg-1
    networks:
      - postgresql

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      #  - /data/pgadmin:/var/lib/pgadmin
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - postgresql

  keycloak:
    image: docker.io/bitnami/keycloak:22
    container_name: keycloak
    environment:
      KEYCLOAK_DATABASE_HOST: pgpool
      KEYCLOAK_DATABASE_PORT: '5432'
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_PASSWORD: 'keycloak123'
      KEYCLOAK_DATABASE_SCHEMA: public
    ports:
      - "80:8080"
    restart: unless-stopped
    depends_on:
      - pgpool
      - pg-0
      - pg-1
    networks:
      - postgresql
