services:
  pgpool:
    image: bitnami/pgpool:4
    container_name: "pgpool"
    # network_mode: "bridge"
    network_mode: "host"
    ports:
      - 5432:5432
    env_file:
      - ../env/pgpool.env
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
    restart: always
    extra_hosts:
      - "pg-0:172.21.139.222"
      - "pg-1:172.21.139.221"
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
